config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
  resources :dashboard, :only => [:index]
  get 'dashboard/create_form_modal(.:format)' => 'dashboard#create_form_modal', as: 'create_form_modal'

  resources :products_services

  delete 'customer_product/:id(.:format)' => 'products_services#destroy_customer_product', as: 'destroy_customer_product'
  delete 'customer_service/:id(.:format)' => 'products_services#destroy_customer_service', as: 'destroy_customer_service'

  get 'customer_product/:id(.:format)' => 'products_services#edit_customer_product', as: 'edit_customer_product'
  get 'customer_service/:id(.:format)' => 'products_services#edit_customer_service', as: 'edit_customer_service'

  post 'customer_product/:id(.:format)' => 'products_services#update_customer_product', as: 'update_customer_product'
  post 'customer_service/:id(.:format)' => 'products_services#update_customer_service', as: 'update_customer_service'

  resources :customers
  post 'customers/:id/' => 'customers#show_range', as: 'customer_range'

  resources :expenses

  resources :services do
    member do
      patch :toggle_enabled
    end
  end

  resources :products do
    member do
      patch :toggle_enabled
    end
  end

  resources :partners do
    member do
      patch :toggle_enabled
    end
  end

  resources :discounts do
    member do
      patch :toggle_enabled
    end
  end
  #path for charts
  get 'customer/products_services_by_day/:id/:range(.:format)' => 'customers#products_services_by_day', as: "customer_products_services_by_day"
  get 'dashboard_index/products_services_by_day' => 'dashboard#products_services_by_day', as: "dashboard_products_services_by_day"
  get 'dashboard_index/products_services_by_week' => 'dashboard#products_services_by_week', as: "dashboard_products_services_by_week"
  get 'dashboard_index/customers_by_sex' => 'dashboard#customers_by_sex', as: "dashboard_customers_by_sex"
  get 'dashboard_index/by_service' => 'dashboard#by_service', as: "dashboard_by_service"


end

app/controllers/dashboard_controller.rb
# noinspection RailsChecklist01
require 'datatables/customer_products_datatable'
require 'datatables/customer_services_datatable'
class DashboardController < ApplicationController

  def index
    @tiles = tiles
    @customer_services_datatable = CustomerServicesDatatable.new(user_id: current_user)
    @customer_products_datatable = CustomerProductsDatatable.new(user_id: current_user)

    # require 'open-uri'
    # file = open('https://meme.eq8.eu/noidea.jpg')
    #
    # current_user.avatar.attach(io: file, filename: 'some-image.jpg')

  end

  def products_services_by_day
    response = [
        {name: "Προϊόντα", data: CustomerProduct.by_user_no_order(current_user).group_by_day(:created_at, format: "%B %d, %Y").count},
        {name: "Υπηρεσίες", data: CustomerService.by_user_no_order(current_user).group_by_day(:created_at, format: "%B %d, %Y").count}
    ]
    render json: response
  end
  def products_services_by_week
    response = [
        {name: "Προϊόντα", data: CustomerProduct.by_user_no_order(current_user).group_by_week(:created_at, format: "%B %d, %Y").count},
        {name: "Υπηρεσίες", data: CustomerService.by_user_no_order(current_user).group_by_week(:created_at, format: "%B %d, %Y").count}
    ]
    render json: response
  end
  def customers_by_sex
    results = Customer.by_user_no_order(current_user).group(:sex).count.transform_keys { |k| k == 'woman' ? "Γυναίκες" : "'Ανδρες" }
    render json: results
  end

  def by_service
    results = CustomerService.by_user_no_order(current_user).eager_load(:service,).group(:name).count
    render json: results
  end

  def create_form_modal
    @customers = Customer.by_user(current_user)
    @products = Product.by_user(current_user).where(enabled: true)
    @services = Service.by_user(current_user).where(enabled: true)
    @partners = Partner.by_user(current_user).where(enabled: true)
    @discounts = Discount.by_user(current_user).where(enabled: true)
    render partial: 'dashboard/create_form_modal'
  end

  def tiles
    my_tiles = Tile.by_user(current_user)

    all_customers = my_tiles.find { |x| x[:inent] == 'all_customers' }
    this_week_customers = my_tiles.find { |x| x[:inent] == 'this_week_customers' }
    if all_customers.nil?
      all_customers = Tile.new(count: 0, sum: 0)
    end
    if this_week_customers.nil?
      this_week_customers = Tile.new(count: 0, sum: 0)
    end

    this_week_products = my_tiles.find { |x| x[:inent] == 'this_week_products' }
    last_week_products = my_tiles.find { |x| x[:inent] == 'last_week_products' }
    if this_week_products.nil?
      this_week_products = Tile.new(count: 0, sum: 0)
    end
    if last_week_products.nil?
      last_week_products = Tile.new(count: 1, sum: 0)
    end
    last_week_percent_product = (this_week_products.count - last_week_products.count) * 100 / last_week_products.count

    this_week_services = my_tiles.find { |x| x[:inent] == 'this_week_services' }
    last_week_services = my_tiles.find { |x| x[:inent] == 'last_week_services' }
    if this_week_services.nil?
      this_week_services = Tile.new(count: 0, sum: 0)
    end
    if last_week_services.nil?
      last_week_services = Tile.new(count: 1, sum: 0)
    end
    last_week_percent_service = (this_week_services.count - last_week_services.count) * 100 / last_week_services.count

    this_week_income = this_week_products.sum + this_week_services.sum
    last_week_income = last_week_products.sum + last_week_services.sum
    if last_week_income == 0
      last_week_income = 1
    end
    last_week_percent_income = (this_week_income - last_week_income) * 100 / last_week_income

    this_week_expenses = my_tiles.find { |x| x[:inent] == 'this_week_expenses' }
    last_week_expenses = my_tiles.find { |x| x[:inent] == 'last_week_expenses' }
    if this_week_expenses.nil?
      this_week_expenses = Tile.new(count: 0, sum: 0)
    end
    if last_week_expenses.nil?
      last_week_expenses = Tile.new(count: 1, sum: 1)
    end
    last_week_percent_expense = (this_week_expenses.sum - last_week_expenses.sum) * 100 / last_week_expenses.sum

    this_week_profit = this_week_income - this_week_expenses.sum
    last_week_profit = last_week_income - last_week_expenses.sum
    if last_week_profit == 0
      last_week_profit = 1
    end
    last_week_percent_profit = (this_week_profit - last_week_profit) * 100 / last_week_profit


    {:total_customers => all_customers.count, :this_week_customers => this_week_customers.count,
     :this_week_products => this_week_products.count, :last_week_percent_product => last_week_percent_product,
     :this_week_services => this_week_services.count, :last_week_percent_service => last_week_percent_service,
     :this_week_income => this_week_income.round(2), :last_week_percent_income => last_week_percent_income.round(0),
     :this_week_expenses => this_week_expenses.sum.round(2), :last_week_percent_expense => last_week_percent_expense.round(0),
     :this_week_profit => this_week_profit.round(2), :last_week_percent_profit => last_week_percent_profit.round(0)}
  end


end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_create_form.html.erb
<div class="x_panel">
  <div class="x_title">
    <h2 id="dd">Προσθήκη Υπηρεσιών και Προϊόντων</h2>
    <h2 class="pull-right green sum">0€</h2>

    <div class="clearfix"></div>
  </div>
  <div class="x_content">

    <%= bootstrap_form_tag url: dashboard_index_path, html: {id: 'add_product_service_form'} do |form| %>
      <%= form.select(:customer_id, @customers.pluck(:name, :id),
                      {label: 'Επιλέξτε Πελάτη', :prompt => 'Δεν έχει επιλεγεί κάποιος'},
                      {class: 'selectpicker form-control', 'data-live-search' => 'true', :required => ''}) %>
      <%= form.select(:partner_id, @partners.pluck(:name, :id),
                      {label: 'Επιλέξτε Συνεργάτη', :prompt => 'Δεν έχει επιλεγεί κάποιος'},
                      {class: 'selectpicker form-control', 'data-live-search' => 'true', :required => ''}) %>
      <div class="col-sm-9">
        <%= form.select(:discount_id, @discounts.collect {|p| [p, p.id, data: {'percent': p.per_cent}]},
                        {label: 'Επιλέξτε Έκπτωση', :prompt => 'Δεν έχει επιλεγεί κάποια'},
                        {class: 'selectpicker', 'data-live-search' => 'true'}) %>
      </div>

      <%= form.number_field :discount_per_cent, label: 'Έκπτωση',
                            data: {toggle: 'tooltip'},
                            min: '0', max: '100',
                            wrapper: {class: 'col-sm-3'} %>


      <%= datepicker_input(form, :created_at) %>

      <hr>
      <div class="accordion" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel">
          <a class="panel-heading collapsed" role="tab" id="headingTwo" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
            <div id="add_service" class="col-sm-1 navbar-right">
              <div class="round round-sm hollow blue">
                <span class="glyphicon glyphicon-plus"></span>
              </div>
            </div>
            <h4 class="panel-title">Υπηρεσίες</h4>
          </a>
          <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo" aria-expanded="false" style="height: 0px;">
            <div class="panel-body">
              <div id="new_services"></div>
            </div>
          </div>
        </div>
        <div class="panel">
          <a class="panel-heading collapsed" role="tab" id="headingOne" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
            <div id="add_product" class="col-sm-1 navbar-right">
              <div class="round round-sm hollow blue">
                <span class="glyphicon glyphicon-plus"></span>
              </div>
            </div>
            <h4 class="panel-title">Προϊόντα</h4>
          </a>
          <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne" aria-expanded="false" style="height: 0px;">
            <div class="panel-body">
              <div id="new_products"></div>
            </div>
          </div>
        </div>
      </div>


      <script>
          $('#add_product').click(function () {
              $('#new_products').append("<%= escape_javascript (render partial: 'dashboard/product_form', locals: {form: form} ,remote: true) %>");
          });
          $('#add_service').click(function () {
              $('#new_services').append("<%= escape_javascript (render partial: 'dashboard/service_form', locals: {form: form} ) %>");
          });
      </script>

      <%= form.form_group do %>
        <%= form.primary 'Προσθήκη' %>
        <h2 class="pull-right green sum">0€</h2>
      <% end %>
      </div>

    <% end %>
    </div>

app/views/dashboard/_create_form_modal.erb
<!-- Modal -->
<div class="modal right fade" id="create_customer_product_service_modal" tabindex="-1" role="dialog" aria-labelledby="create_customer_product_service_modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel2">Προσθέστε συναλλαγή</h4>
      </div>
      <%= bootstrap_form_tag url: products_services_path, html: {id: 'add_product_service_form'} do |form| %>
        <div class="modal-body">
          <%= form.select(:customer_id, @customers.pluck(:name, :id),
                          {label: 'Επιλέξτε Πελάτη', :prompt => 'Δεν έχει επιλεγεί κάποιος'},
                          {class: 'selectpicker form-control', 'data-live-search' => 'true', :required => ''}) %>
          <%= form.select(:partner_id, @partners.pluck(:name, :id),
                          {label: 'Επιλέξτε Συνεργάτη', :prompt => 'Δεν έχει επιλεγεί κάποιος'},
                          {class: 'selectpicker form-control', 'data-live-search' => 'true', :required => ''}) %>
          <div class="col-sm-9">
            <%= form.select(:discount_id, @discounts.collect { |p| [p, p.id, data: {'percent': p.per_cent}] },
                            {label: 'Επιλέξτε Έκπτωση', :prompt => 'Δεν έχει επιλεγεί κάποια'},
                            {class: 'selectpicker', 'data-live-search' => 'true'}) %>
          </div>
          <%= form.number_field :discount_per_cent, label: 'Έκπτωση',
                                data: {toggle: 'tooltip'},
                                min: '0', max: '100',
                                wrapper: {class: 'col-sm-3'} %>
          <%= datepicker_input(form, :created_at) %>
          <hr>
          <div class="accordion" id="accordion" role="tablist" aria-multiselectable="true">
            <div class="panel">
              <a class="panel-heading collapsed" role="tab" id="headingTwo" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                <div id="add_service" class="col-sm-1 navbar-right">
                  <div class="round round-sm hollow blue">
                    <span class="glyphicon glyphicon-plus"></span>
                  </div>
                </div>
                <h4 class="panel-title">Υπηρεσίες</h4>
              </a>
              <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo" aria-expanded="false" style="height: 0px;">
                <div class="panel-body">
                  <div id="new_services"></div>
                </div>
              </div>
            </div>
            <div class="panel">
              <a class="panel-heading collapsed" role="tab" id="headingOne" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                <div id="add_product" class="col-sm-1 navbar-right">
                  <div class="round round-sm hollow blue">
                    <span class="glyphicon glyphicon-plus"></span>
                  </div>
                </div>
                <h4 class="panel-title">Προϊόντα</h4>
              </a>
              <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne" aria-expanded="false" style="height: 0px;">
                <div class="panel-body">
                  <div id="new_products"></div>
                </div>
              </div>
            </div>
          </div>

          <script>
              $('#add_product').click(function () {
                  $('#new_products').append("<%= escape_javascript(render partial: 'products_services/product_form', locals: {form: form} ,remote: true) %>");
              });
              $('#add_service').click(function () {
                  $('#new_services').append("<%= escape_javascript(render partial: 'products_services/service_form', locals: {form: form},remote: true ) %>");
              });
          </script>

        </div>
        <div class="modal-footer">
          <%= form.form_group do %>
            <%= form.primary 'Προσθήκη' %>
            <h3 class="pull-right green sum">0€</h3>
          <% end %>
      <% end %>

      </div>
    </div><!-- modal-content -->

  </div><!-- modal-dialog -->
</div><!-- modal -->

app/views/dashboard/_create_form_modal2.erb
Hello!!!!

app/views/dashboard/_product_form.html.erb
<div class="panel-body">
  <%= form.fields_for 'customer_products[]', CustomerProduct.new do |c| %>
    <a class="more_fields_toggle pull-right"><i class="glyphicon glyphicon-chevron-down"></i></a>
    <%= c.select(:product_id, @products.collect {|p| [p, p.id, data: {'price': p.price}]},
                 {label: 'Επιλέξτε Προϊόν', :prompt => 'Δεν έχει επιλεγεί κάποιο'},
                 {class: 'selectpicker in_price', 'data-live-search' => 'true'}) %>

    <div class="more_fields" style="display: none;">
      <%= c.select(:partner_id, @partners.pluck(:name, :id),
                   {label: 'Επιλέξτε Συνεργάτη', :prompt => 'Δεν έχει επιλεγεί κάποιος'},
                   {class: 'selectpicker form-control', 'data-live-search' => 'true'}) %>
      <%= c.number_field :amount, label: 'Ποσότητα',
                         class: :amount,
                         data: {toggle: 'tooltip'},
                         title: 'αφήστε κενό για ποσότητα ίση με ένα',
                         wrapper: {class: 'col-sm-6'} %>
      <%= c.number_field :price, label: 'Τιμή',
                         class: 'text_field custom_price',
                         step: :any,
                         data: {toggle: 'tooltip'},
                         title: 'αφήστε κενό για την προκαθορισμένη τιμή',
                         wrapper: {class: 'col-sm-6'} %>
      <%= c.text_field :comment, label: 'Σχόλιο' %>
    </div>
  <% end %>
</div>

app/views/dashboard/_services_table.erb
<div class="x_panel">
  <div class="x_title">
    <h2>Υπηρεσίες</h2>
    <div class="clearfix"></div>
  </div>
  <div class="x_content">
    <table id="datatable-customer_services" class="table table-striped table-bordered" cellspacing="0" width="100%">
      <thead>
      <tr>
        <th>Όνομα</th>
        <th>Υπηρεσία</th>
        <th>Συνεργάτης</th>
        <th>Ποσότητα - Τιμή</th>
        <th>Σχόλιο</th>
        <th>Ημ/Ώρα</th>
        <th>Διαγραφή</th>

      </tr>
      </thead>
      <tbody>
      <% @customer_services.each {|record| %>
        <tr>
          <%= row(record.customer.name) %>
          <%= row(record.service.to_s_name_description) %>
          <%= row(record.partner.to_s) %>
          <%= row_with_tooltip(record.amount_price,
                               record.price_tooltip,
                               "data-sort='#{record.total_paid}'") %>
          <%= row(record.comment) %>
          <%= row_with_tooltip(record.created_at_s,
                               time_ago_in_words(record.created_at),
                               "data-sort='#{record.created_at}'") %>
          <%= delete_row(destroy_customer_service_path(record)) %>

        </tr>
      <% } %>
      </tbody>
    </table>
  </div>
</div>

app/views/dashboard/_tmp_form.html.erb
Δημιουργία
Ενημέρωση
Διαγραφή
Προσθήκη
Επιλέξτε
Πίσω
Καταχώρηση

Συνολικοί
απο την προηγούμενη εβδομάδα
τελευταίες 7 μέρες

Πελάτη
Πελάτης
Πελάτες

Συνεργάτη
Συνεργάτης
Συνεργάτες
Συνεργατων

Προϊόν
Προϊόντα
Προϊόντων
Προϊόντος

Υπηρεσίας
Υπηρεσία
Υπηρεσιών
Υπηρεσίες

Έξοδο
Έξοδα
Εξόδου


Όνομα
Τηλέφωνο
Σχόλιο
Περιγραφή
Τιμή
Ποσότητα
Ημ/Ώρα
Λογός
Ενεργός

αφήστε κενό για ποσότητα ίση με ένα
αφήστε κενό για την προκαθορισμένη τιμή
Σύνολο

Δεν έχει επιλεγεί κάποιο

Ρυθμίσεις
Αποσύνδεση


Αρχική σελίδα
Προφίλ

Επιβεβαίωση του λογαριασμού
Αλλαγή κωδικόύ





Όνομα χρήστη
Κωδικός
Επιβεβαίωση κωδικού
Τωρινός κωδικός
Νέος κωδικός
Εγγραφή
Σύνδεση
Συνδεθείτε στον λογαριασμό σας
Δημιουργία λογαριασμού

Δεν έχετε λογαριασμό



χαρακτήρες το ελάχιστο


( χρειαζόμαστε τον τωρινό σας κωδικό για να επιβεβαιώσουμε τις αλλαγές )
Έξοδα

app/views/dashboard/_total_tiles.html.erb
<!-- top tiles -->
<div class="tile_count" id="tiles" style="display: none;">
  <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
    <span class="count_top"><i class="fa fa-user"></i> Συνολικοί Πελάτες</span>
    <div class="count blue"><%= @tiles[:total_customers] %></div>
    <span class="count_bottom"><i class="green"><%= @tiles[:this_week_customers] %> </i> νέοι αυτή την εβδομάδα</span>
  </div>
  <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
    <span class="count_top"><i class="glyphicon glyphicon-scissors"></i> Υπηρεσίες εβδομάδας</span>
    <div class="count pink"><%= @tiles[:this_week_services] %></div>
    <%= percent_tile(@tiles[:last_week_percent_service], 'απο την προηγούμενη εβδομάδα') %>
  </div>
  <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
    <span class="count_top"><i class="glyphicon glyphicon-ice-lolly"></i> Προϊόντα εβδομάδας</span>
    <div class="count pink"><%= @tiles[:this_week_products] %></div>
    <%= percent_tile(@tiles[:last_week_percent_product], 'απο την προηγούμενη εβδομάδα') %>
  </div>
  <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
    <span class="count_top"><i class="glyphicon glyphicon-hand-up"></i> Έσοδα εβδομάδας</span>
    <div class="count aero"><%= @tiles[:this_week_income] %>€</div>
    <%= percent_tile(@tiles[:last_week_percent_income], 'απο την προηγούμενη εβδομάδα') %>
  </div>
  <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
    <span class="count_top"><i class="glyphicon glyphicon-hand-down"></i> Έξοδα εβδομάδας</span>
    <div class="count red"><%= @tiles[:this_week_expenses] %>€</div>
    <%= percent_tile(@tiles[:last_week_percent_expense], 'απο την προηγούμενη εβδομάδα') %>
  </div>
  <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
    <span class="count_top"><i class="glyphicon glyphicon-hand-right"></i> Κέρδος εβδομάδας</span>
    <div class="count green"><%= @tiles[:this_week_profit] %>€</div>
    <%= percent_tile(@tiles[:last_week_percent_profit], 'απο την προηγούμενη εβδομάδα') %>
  </div>
</div>
<!-- /top tiles -->

app/views/dashboard/edit_customer_product.html.erb
<div class="col-md-4 col-sm-4 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2 id="dd">Ενημέρωση Προϊόντoς</h2>
      <h2 class="pull-right green sum">0€</h2>

      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <div class="panel-body">
        <%= bootstrap_form_tag url: {controller: 'dashboard', action: 'update_customer_product'}, html: {id: 'add_product_service_form'} do |form| %>
          <%= form.fields_for @record, url: {controller: 'dashboard', action: 'update_customer_product'} do |f| %>
            <%= f.select(:customer_id, @customers.pluck(:name, :id),
                         {label: 'Επιλέξτε Πελάτη', :prompt => 'Δεν έχει επιλεγεί κάποιος'},
                         {class: 'selectpicker form-control', 'data-live-search' => 'true', :required => ''}) %>

            <%= f.select(:product_id, @products.collect {|p| [p, p.id, data: {'price': p.price}]},
                         {label: 'Επιλέξτε Προϊόν', :prompt => 'Δεν έχει επιλεγεί κάποιο'},
                         {class: 'selectpicker in_price', 'data-live-search' => 'true'}) %>
            <%= datepicker_input(form, :created_at) %>

            <%= f.number_field :amount, label: 'Ποσότητα',
                               class: :amount,
                               data: {toggle: 'tooltip'},
                               title: 'αφήστε κενό για ποσότητα ίση με ένα',
                               wrapper: {class: 'col-sm-6'} %>

            <%= f.number_field :price, label: 'Τιμή',
                               class: 'text_field custom_price',
                               step: :any,
                               data: {toggle: 'tooltip'},
                               title: 'αφήστε κενό για την προκαθορισμένη τιμή',
                               wrapper: {class: 'col-sm-6'} %>
            <div class="col-sm-9" style="padding: 25px">
              <%= form.check_box :student_discount, label: 'Φοιτητική έκπτωση',
                                 class: 'js-switch' %>
            </div>

            <%= form.number_field :discount, label: 'Έκπτωση',
                                  data: {toggle: 'tooltip'},
                                  title: 'αφήστε κενό για ποσότητα ίση με ένα',
                                  min: '0', max: '100',
                                  wrapper: {class: 'col-sm-3'} %>
            <%= f.text_field :comment, label: 'Σχόλιο' %>
            <%= f.form_group do %>
              <%= f.primary 'Ενημέρωση' %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "dashboard.js", 'data-turbolinks-track' => true %>
<% end %>
<%= render 'dashboard/total_tiles' %>
<div class="col-md-6 col-sm-6 col-xs-12 ">
  <%= render 'dashboard/charts/by_service' %>
</div>

<div class="col-md-6 col-sm-6 col-xs-12 ">
  <%= render 'dashboard/charts/products_services_by_week' %>
</div>
<div class="col-xl-6 col-lg-12 col-md-12 col-sm-12 col-xs-12 pull-right">
  <%= render 'products_services/services_table' %>
</div>

<div class="col-xl-6 col-lg-12 col-md-12 col-sm-12 col-xs-12 pull-right">
  <%= render 'products_services/products_table' %>
</div>

<div id="form_modal"></div>
<a data-toggle="modal" data-target="#create_customer_product_service_modal" class="float">
  <i class="fa fa-plus my-float"></i>
</a>