config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#index'
  resources :dashboard, :only => [:index]
  get 'dashboard/create_form_modal(.:format)' => 'dashboard#create_form_modal', as: 'create_form_modal'

  resources :products_services

  delete 'customer_product/:id(.:format)' => 'products_services#destroy_customer_product', as: 'destroy_customer_product'
  delete 'customer_service/:id(.:format)' => 'products_services#destroy_customer_service', as: 'destroy_customer_service'

  get 'customer_product/:id(.:format)' => 'products_services#edit_customer_product', as: 'edit_customer_product'
  get 'customer_service/:id(.:format)' => 'products_services#edit_customer_service', as: 'edit_customer_service'

  post 'customer_product/:id(.:format)' => 'products_services#update_customer_product', as: 'update_customer_product'
  post 'customer_service/:id(.:format)' => 'products_services#update_customer_service', as: 'update_customer_service'

  resources :customers
  post 'customers/:id/' => 'customers#show_range', as: 'customer_range'

  resources :expenses

  resources :services do
    member do
      patch :toggle_enabled
    end
  end

  resources :products do
    member do
      patch :toggle_enabled
    end
  end

  resources :partners do
    member do
      patch :toggle_enabled
    end
  end

  resources :discounts do
    member do
      patch :toggle_enabled
    end
  end
  #path for charts
  get 'customer/products_services_by_day/:id/:range(.:format)' => 'customers#products_services_by_day', as: "customer_products_services_by_day"
  get 'dashboard_index/products_services_by_day' => 'dashboard#products_services_by_day', as: "dashboard_products_services_by_day"
  get 'dashboard_index/products_services_by_week' => 'dashboard#products_services_by_week', as: "dashboard_products_services_by_week"
  get 'dashboard_index/customers_by_sex' => 'dashboard#customers_by_sex', as: "dashboard_customers_by_sex"
  get 'dashboard_index/by_service' => 'dashboard#by_service', as: "dashboard_by_service"


end

app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
  belongs_to :user
  scope :by_user, ->(current_user) {where(user: current_user).order(name: :desc)}
  scope :by_user_no_order, ->(current_user) {where(user: current_user)}

  has_many :customer_products, :dependent => :restrict_with_error
  has_many :products, through: :customer_products, :dependent => :restrict_with_error

  has_many :customer_services, :dependent => :restrict_with_error
  has_many :services, through: :customer_services, :dependent => :restrict_with_error

  enum sex: [:woman, :man]

  def create_with_user(current_user)
    self.user = current_user if user.nil?
    save
  end

  def to_s
    "#{name}"
  end

  def sex_to_s
    woman? ? "Γυναίκα" : "'Ανδρας"
  end
end

app/controllers/customers_controller.rb
require 'datatables/customers_datatable'
require 'datatables/services_by_customer_datatable'
require 'datatables/products_by_customer_datatable'

class CustomersController < ApplicationController
  require 'ml'

  def index
    @records = Customer.by_user(current_user)
    @customers_datatable = CustomersDatatable.new(user_id: current_user)
  end

  def show
    @record = Customer.by_user(current_user).find(params[:id])
    @services_by_customer_datatable = ServicesByCustomerDatatable.new(user_id: current_user, range: between_where(@range), customer: @record)
    @products_by_customer_datatable = ProductsByCustomerDatatable.new(user_id: current_user, range: between_where(@range), customer: @record)
    tiles
  end

  def between_where(range)
    if not range or range[:start] == ""
      range = {}
      range[:start] = 0
      range[:end] = Time.now.to_i * 1000
      print "between_where none:" + range.to_s
    end

    s = DateTime.strptime((range[:start].to_f / 1000).to_s, '%s')
    e = DateTime.strptime((range[:end].to_f / 1000).to_s, '%s')
    {:created_at => s..e}
  end

  def show_range
    @record = Customer.by_user(current_user).find(params[:id])
    @range = {start: params[:start], end: params[:end], label: params[:label]}
    @services_by_customer_datatable = ServicesByCustomerDatatable.new(user_id: current_user, range: between_where(@range), customer: @record)
    @products_by_customer_datatable = ProductsByCustomerDatatable.new(user_id: current_user, range: between_where(@range), customer: @record)
    tiles
    render partial: 'customers/show_content'
  end

  def create
    @record = Customer.new(customer_params).create_with_user(current_user)
    redirect_to customers_path
  end

  def edit
    @records = Customer.by_user(current_user)
    @record = Customer.by_user(current_user).find(params[:id])
    @customers_datatable = CustomersDatatable.new(user_id: current_user)
  end

  def update
    @record = Customer.by_user(current_user).find(params[:id])
    if @record.update_attributes(customer_params)
      redirect_to customers_path
    else
      render 'edit'
    end
  end

  def destroy
    @record = Customer.by_user(current_user).find(params[:id])
    @record.destroy
    redirect_to customers_path
  end


  def products_services_by_day
    @record = Customer.by_user(current_user).find(params[:id])

    @range = Rack::Utils.parse_nested_query(params[:range]).symbolize_keys
    print @range
    dates = []

    if @range[:label] == "All"
      predictions = predict_next_visits(3)
      if predictions
        predictions = predictions.map { |p| p[:next_visit].to_date }
        start_date = Time.now
        end_date = predictions[-1]
        start_date.to_date.upto(end_date.to_date) do |date|
          if predictions.include? date
            dates.append([date.strftime("%B %d, %Y"), 1])
          else
            dates.append([date.strftime("%B %d, %Y"), 0])
          end
        end
      end
    end
    predictions = {name: "Predict", data: dates}

    response = [
        {name: "Services", data: @record.customer_services.where(between_where(@range)).group_by_day(:created_at, format: "%B %d, %Y").count},
        {name: "Products", data: @record.customer_products.where(between_where(@range)).group_by_day(:created_at, format: "%B %d, %Y").count},
        predictions
    ]
    render json: response
  end

  def customer_params
    params.require(:customer).permit(:name, :phone_1, :phone_2, :sex, :comment, :customer_range)
  end

  def tiles
    f = @record.customer_services.order(:created_at).first.created_at
    l = @record.customer_services.order(:created_at).last.created_at

    months_active = (l.year * 12 + l.month) - (f.year * 12 + f.month)

    visits = @record.customer_services.distinct.count(:created_at)
    av_visits = (visits.to_f / months_active.to_f).round(2)
    profit = (@record.customer_services.sum("price * amount") + @record.customer_services.sum("price * amount")).round(2)
    av_profit = (profit.to_f / months_active.to_f).round(2)
    services = @record.customer_services.count
    av_services = (services.to_f / months_active.to_f).round(2)
    products = @record.customer_products.count
    av_products = (products.to_f / months_active.to_f).round(2)
    predictions = predict_next_visits(0)
    if predictions.nil?
      prediction = {next_visit: "unknown", in_days: "unknown"}
    else
      prediction = predictions[0]
    end
    @tiles = {
        :months_active => months_active,
        :visits => visits,
        :av_visits => av_visits,
        :profit => profit,
        :av_profit => av_profit,
        :services => services,
        :av_services => av_services,
        :products => products,
        :av_products => av_products,
        :next_visit => prediction[:next_visit],
        :in_days => prediction[:in_days]
    }
  end

  def build_model
    model = ML::Regress.new
    visits = @record.customer_services.distinct.order(created_at: :asc).pluck(:created_at)
    if visits.length < 5
      return nil
    end
    y = visits.map do |record, i|
      ((record - visits[0]).to_i / 1.day)
    end
    y = y.uniq
    x = []
    for i in 0..(y.length - 1)
      x.push(i)
    end

    # Load training data
    model.regress(x, y, 2)
    [visits[0], model]
  end

  def predict_next_visits(n)
    (first_visit, model) = build_model
    if first_visit.nil?
      return nil
    end
    predictions = []
    (0..n).each { |i|
      in_days = model.predict_in_future(i).days
      next_visit = first_visit + in_days
      predictions.push({next_visit: first_visit + in_days, in_days: (next_visit - Time.now).to_i / 1.day})
    }
    predictions
  end


end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_chart_test.erb
<% unless @range %>
  <% @range = {label: "All", start: "", end: ""} %>
<% end %>
<%= x_panel 'Υπηρεσίες και Προϊόντα', '' do %>
  <%= line_chart customer_products_services_by_day_url(@record.id, @range.to_query), discrete: true %>
<% end %>

app/views/customers/_create_form.html.erb
<div class="x_panel">
  <div class="x_title">
    <h2>Δημιουργία Πελάτη</h2>
    <div class="clearfix"></div>
  </div>
  <div class="x_content">
    <%= bootstrap_form_for :customer, url: {controller: 'customers', action: 'create'} do |f| %>
      <%= f.text_field :name, label: 'Όνομα' %>
      <%= f.select :sex, [['Γυναίκα', :woman], ['Άνδρας', :man]], {label: 'Επιλέξτε φύλο:'}, {class: 'selectpicker'} %>
      <%= f.phone_field :phone_1, label: 'Τηλέφωνο 1' %>
      <%= f.phone_field :phone_2, label: 'Τηλέφωνο 2' %>
      <%= f.text_field :comment, label: 'Σχόλιο' %>
      <%= f.form_group do %>
        <%= f.primary 'Δημιουργία' %>
      <% end %>
    <% end %>
  </div>
</div>

<script>
    $('.selectpicker').selectpicker();
</script>

app/views/customers/_customer_tiles.html.erb
<!-- top tiles -->
<div class="tile_count col-md-12 " id="tiles" style="display: none;">
  <div class="col-md-3 col-sm-4 col-xs-6 tile_stats_count">
    <span class="count_top"><i class="fa fa-user"></i> Επισκέψεις - Μήνες</span>
    <div class="count blue"><%= @tiles[:visits].to_s + " - " + @tiles[:months_active].to_s %></div>
    <span class="count_bottom"><i class="green"><%= @tiles[:av_visits] %> </i> μ.ο. επισκέψεων ανά μήνα</span>
  </div>
  <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
    <span class="count_top"><i class="glyphicon glyphicon-scissors"></i> Συνολικό κέρδος</span>
    <div class="count pink"><%= @tiles[:profit] %></div>
    <%= regular_tile(@tiles[:av_profit], 'μ.ο. ανά μήνα') %>
  </div>
  <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
    <span class="count_top"><i class="glyphicon glyphicon-ice-lolly"></i> Συνολικές Υπηρεσίες</span>
    <div class="count pink"><%= @tiles[:services] %></div>
    <%= regular_tile(@tiles[:av_services], 'μ.ο. ανά μήνα') %>
  </div>
  <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
    <span class="count_top"><i class="glyphicon glyphicon-ice-lolly"></i> Συνολικά Προϊόντα</span>
    <div class="count pink"><%= @tiles[:products] %></div>
    <%= regular_tile(@tiles[:av_products], 'μ.ο. ανά μήνα') %>
  </div>
  <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
    <span class="count_top"><i class="glyphicon glyphicon-ice-lolly"></i> Πρόβλεψη</span>
    <div class="count pink"><%= @tiles[:next_visit] %></div>
    <%= regular_tile(@tiles[:in_days], 'επομένη επίσκεψη') %>
  </div>
</div>
<!-- /top tiles -->

app/views/customers/_edit_form.html.erb
<div class="x_panel">
  <div class="x_title">
    <h2>Ενημέρωση Πελάτη</h2>
    <div class="clearfix"></div>
  </div>
  <div class="x_content">
    <%= bootstrap_form_for @record, url: {controller: 'customers', action: 'update'} do |f| %>
      <%= f.text_field :name, label: 'Όνομα' %>
      <%= f.select :sex, [['Γυναίκα', :woman], ['Άνδρας', :man]], {label: 'Επιλέξτε φύλο:'}, {class: 'selectpicker'} %>
      <%= f.phone_field :phone_1, label: 'Τηλέφωνο 1' %>
      <%= f.phone_field :phone_2, label: 'Τηλέφωνο 2' %>
      <%= f.text_field :comment, label: 'Σχόλιο' %>
      <%= f.form_group do %>
        <%= f.primary 'Ενημέρωση' %>
      <% end %>
    <% end %>
  </div>
</div>
<script>
    $('.selectpicker').selectpicker();
</script>

app/views/customers/_show_content.erb
<div class="col-md-6 col-sm-6 col-xs-12">
  <%= render 'customers/chart_test' %>
</div>
<div class="col-md-6 col-sm-6 col-xs-12 pull-right">
  <%= render 'customers/table_services' %>
</div>
<div class="col-md-6 col-sm-6 col-xs-12 pull-right">
  <%= render 'customers/table_products' %>
</div>

app/views/customers/_table.erb
<%= x_panel 'Πελάτες', '' do %>
  <%= render_datatable(@customers_datatable, buttons: false) %>
<% end %>

app/views/customers/_table_products.erb
<%= x_panel 'Προϊόντα', '' do %>
  <%= render_datatable(@products_by_customer_datatable, buttons: false) %>
<% end %>

app/views/customers/_table_services.erb
<%= x_panel 'Υπηρεσίες', '' do %>
  <%= render_datatable(@services_by_customer_datatable, buttons: false) %>
<% end %>

app/views/customers/_tiles.html.erb
<div class="col-md-6 col-sm-6 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2>Line graph
        <small>Sessions</small>
      </h2>
      <ul class="nav navbar-right panel_toolbox">
        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Settings 1</a>
            </li>
            <li><a href="#">Settings 2</a>
            </li>
          </ul>
        </li>
        <li><a class="close-link"><i class="fa fa-close"></i></a>
        </li>
      </ul>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <canvas id="lineChart"></canvas>
    </div>
  </div>
</div>

app/views/customers/edit.html.erb
<div class="col-md-8 col-sm-8 col-xs-12">
  <%= render 'customers/table' %>
</div>
<div class="col-md-4 col-sm-4 col-xs-12">
  <%= render 'customers/edit_form' %>
</div>

app/views/customers/index.html.erb
<div class="col-md-8 col-sm-8 col-xs-12">
  <%= render 'customers/table' %>
</div>
<div class="col-md-4 col-sm-4 col-xs-12">
  <%= render 'customers/create_form' %>
</div>

app/views/customers/show.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "customers.js", 'data-turbolinks-track' => true %>
<% end %>
<%= render 'customers/customer_tiles' %>

<ul class="nav navbar-nav navbar-right" style="margin-bottom: 5px;">
  <%= bootstrap_form_tag url: dashboard_index_path, html: {id: 'add_product_service_form'} do |f| %>
    <%= f.text_field :date_range, data: {provide: 'datepicker'}, class: 'date_range', label: "Εύρος αναζήτησης" %>
  <% end %>
</ul>
<div id="show_content"></div>